### ISSUE TITLE
Add Travis-CI or Circle-CI

### ISSUE THREAD

**Issue by pdehaan** [lmorchard/ThemesRFun#3]
We should probably hook up Circle-CI (or Travis-CI) so that we can run [at a minimum] ESLint and maybe build the extension on each PR so we know everything is kosher.

❤️

**Comment by lmorchard** [comment]
Basic config here, though pondering adding some auto-deployment with some env vars and `npm run release:dev`

https://github.com/lmorchard/ThemesRFun/commit/70e55ab050da3f657b3f8d618c76b06eb6589f38

**Comment by lmorchard** [comment]
Filed https://github.com/lmorchard/ThemesRFun/issues/7
